version: "3.2"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /mnt
    command: /usr/share/python3/app/bin/python /mnt/server/server.py
    ports:
      - "127.0.0.1:80:80"